export const ROLE = {
  ADMIN_MANAGER: "ADMIN_MANAGER",
  ADMIN_TECH: "ADMIN_TECH",
  MANAGER: "MANAGER",
  TECH: "TECH",
  MAGASIN: "MAGASIN",
  COORDINATOR: "COORDINATOR",
};

export interface ROLE {
  ADMIN_MANAGER: "ADMIN_MANAGER";
  ADMIN_TECH: "ADMIN_TECH";
  MANAGER: "MANAGER";
  TECH: "TECH";
  MAGASIN: "MAGASIN";
  COORDINATOR: "COORDINATOR";
}
